name = "lodash-do"
route = { pattern = "*/*", zone_name = "lodash.do" }
main = "dist/index.mjs"
compatibility_date = "2022-08-25"

services = [
  { binding = "CTX", service = "ctx-do", environment = "production" }
]

logpush = true

[build]
command = "npm run build"
 
[build.upload]
format = "modules"

[miniflare]
kv_persist = "./data/"

[miniflare.mounts]
ctx-do = "../ctx.do"